<<<<<<< HEAD
DROP TABLE IF EXISTS strain;
DROP TABLE IF EXISTS grow;
DROP TABLE IF EXISTS TIMESTAMP;

CREATE TABLE strain (
  strain_id INTEGER PRIMARY KEY AUTOINCREMENT,
  strain_name TEXT UNIQUE NOT NULL
);

CREATE TABLE grow (
  grow_id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY (grow_id) REFERENCES strain (strain_id),
  stage TEXT NOT NULL,
  week INTEGER NOT NULL
  
);

CREATE TABLE TIMESTAMP (
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
=======
DROP TABLE IF EXISTS strain;
DROP TABLE IF EXISTS grow;
DROP TABLE IF EXISTS TIMESTAMP;

CREATE TABLE strain (
  strain_id INTEGER PRIMARY KEY AUTOINCREMENT,
  strain_name TEXT UNIQUE NOT NULL
);

CREATE TABLE grow (
  grow_id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY (grow_id) REFERENCES strain (strain_id),
  stage TEXT NOT NULL,
  week INTEGER NOT NULL
  
);

CREATE TABLE TIMESTAMP (
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
>>>>>>> 0f9b1bba6b66932c0aedb0dd06fae9c57eea0675
