[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP Async WebServer
    PubSubClient
    ArduinoJson
    mbedtls
    BLEPeripheral
    Update
build_flags = 
    -I include
    -I src
